// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Models/SeiMetadata.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Models/SeiMetadata.proto</summary>
public static partial class SeiMetadataReflection {

  #region Descriptor
  /// <summary>File descriptor for Models/SeiMetadata.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SeiMetadataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChhNb2RlbHMvU2VpTWV0YWRhdGEucHJvdG8i+AQKC1NlaU1ldGFkYXRhEg8K",
          "B3ZlcnNpb24YASABKA0SJQoKZ2Vhcl9zdGF0ZRgCIAEoDjIRLlNlaU1ldGFk",
          "YXRhLkdlYXISFAoMZnJhbWVfc2VxX25vGAMgASgEEhkKEXZlaGljbGVfc3Bl",
          "ZWRfbXBzGAQgASgCEiIKGmFjY2VsZXJhdG9yX3BlZGFsX3Bvc2l0aW9uGAUg",
          "ASgCEhwKFHN0ZWVyaW5nX3doZWVsX2FuZ2xlGAYgASgCEhcKD2JsaW5rZXJf",
          "b25fbGVmdBgHIAEoCBIYChBibGlua2VyX29uX3JpZ2h0GAggASgIEhUKDWJy",
          "YWtlX2FwcGxpZWQYCSABKAgSNAoPYXV0b3BpbG90X3N0YXRlGAogASgOMhsu",
          "U2VpTWV0YWRhdGEuQXV0b3BpbG90U3RhdGUSFAoMbGF0aXR1ZGVfZGVnGAsg",
          "ASgBEhUKDWxvbmdpdHVkZV9kZWcYDCABKAESEwoLaGVhZGluZ19kZWcYDSAB",
          "KAESIgoabGluZWFyX2FjY2VsZXJhdGlvbl9tcHMyX3gYDiABKAESIgoabGlu",
          "ZWFyX2FjY2VsZXJhdGlvbl9tcHMyX3kYDyABKAESIgoabGluZWFyX2FjY2Vs",
          "ZXJhdGlvbl9tcHMyX3oYECABKAEiSQoER2VhchINCglHRUFSX1BBUksQABIO",
          "CgpHRUFSX0RSSVZFEAESEAoMR0VBUl9SRVZFUlNFEAISEAoMR0VBUl9ORVVU",
          "UkFMEAMiRQoOQXV0b3BpbG90U3RhdGUSCAoETk9ORRAAEhAKDFNFTEZfRFJJ",
          "VklORxABEg0KCUFVVE9TVEVFUhACEggKBFRBQ0MQA2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::SeiMetadata), global::SeiMetadata.Parser, new[]{ "Version", "GearState", "FrameSeqNo", "VehicleSpeedMps", "AcceleratorPedalPosition", "SteeringWheelAngle", "BlinkerOnLeft", "BlinkerOnRight", "BrakeApplied", "AutopilotState", "LatitudeDeg", "LongitudeDeg", "HeadingDeg", "LinearAccelerationMps2X", "LinearAccelerationMps2Y", "LinearAccelerationMps2Z" }, null, new[]{ typeof(global::SeiMetadata.Types.Gear), typeof(global::SeiMetadata.Types.AutopilotState) }, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// SEI (Supplemental Enhancement Information) metadata embedded in Tesla dashcam video streams.
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class SeiMetadata : pb::IMessage<SeiMetadata>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SeiMetadata> _parser = new pb::MessageParser<SeiMetadata>(() => new SeiMetadata());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SeiMetadata> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SeiMetadataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SeiMetadata() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SeiMetadata(SeiMetadata other) : this() {
    version_ = other.version_;
    gearState_ = other.gearState_;
    frameSeqNo_ = other.frameSeqNo_;
    vehicleSpeedMps_ = other.vehicleSpeedMps_;
    acceleratorPedalPosition_ = other.acceleratorPedalPosition_;
    steeringWheelAngle_ = other.steeringWheelAngle_;
    blinkerOnLeft_ = other.blinkerOnLeft_;
    blinkerOnRight_ = other.blinkerOnRight_;
    brakeApplied_ = other.brakeApplied_;
    autopilotState_ = other.autopilotState_;
    latitudeDeg_ = other.latitudeDeg_;
    longitudeDeg_ = other.longitudeDeg_;
    headingDeg_ = other.headingDeg_;
    linearAccelerationMps2X_ = other.linearAccelerationMps2X_;
    linearAccelerationMps2Y_ = other.linearAccelerationMps2Y_;
    linearAccelerationMps2Z_ = other.linearAccelerationMps2Z_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SeiMetadata Clone() {
    return new SeiMetadata(this);
  }

  /// <summary>Field number for the "version" field.</summary>
  public const int VersionFieldNumber = 1;
  private uint version_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Version {
    get { return version_; }
    set {
      version_ = value;
    }
  }

  /// <summary>Field number for the "gear_state" field.</summary>
  public const int GearStateFieldNumber = 2;
  private global::SeiMetadata.Types.Gear gearState_ = global::SeiMetadata.Types.Gear.Park;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::SeiMetadata.Types.Gear GearState {
    get { return gearState_; }
    set {
      gearState_ = value;
    }
  }

  /// <summary>Field number for the "frame_seq_no" field.</summary>
  public const int FrameSeqNoFieldNumber = 3;
  private ulong frameSeqNo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong FrameSeqNo {
    get { return frameSeqNo_; }
    set {
      frameSeqNo_ = value;
    }
  }

  /// <summary>Field number for the "vehicle_speed_mps" field.</summary>
  public const int VehicleSpeedMpsFieldNumber = 4;
  private float vehicleSpeedMps_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float VehicleSpeedMps {
    get { return vehicleSpeedMps_; }
    set {
      vehicleSpeedMps_ = value;
    }
  }

  /// <summary>Field number for the "accelerator_pedal_position" field.</summary>
  public const int AcceleratorPedalPositionFieldNumber = 5;
  private float acceleratorPedalPosition_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float AcceleratorPedalPosition {
    get { return acceleratorPedalPosition_; }
    set {
      acceleratorPedalPosition_ = value;
    }
  }

  /// <summary>Field number for the "steering_wheel_angle" field.</summary>
  public const int SteeringWheelAngleFieldNumber = 6;
  private float steeringWheelAngle_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float SteeringWheelAngle {
    get { return steeringWheelAngle_; }
    set {
      steeringWheelAngle_ = value;
    }
  }

  /// <summary>Field number for the "blinker_on_left" field.</summary>
  public const int BlinkerOnLeftFieldNumber = 7;
  private bool blinkerOnLeft_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool BlinkerOnLeft {
    get { return blinkerOnLeft_; }
    set {
      blinkerOnLeft_ = value;
    }
  }

  /// <summary>Field number for the "blinker_on_right" field.</summary>
  public const int BlinkerOnRightFieldNumber = 8;
  private bool blinkerOnRight_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool BlinkerOnRight {
    get { return blinkerOnRight_; }
    set {
      blinkerOnRight_ = value;
    }
  }

  /// <summary>Field number for the "brake_applied" field.</summary>
  public const int BrakeAppliedFieldNumber = 9;
  private bool brakeApplied_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool BrakeApplied {
    get { return brakeApplied_; }
    set {
      brakeApplied_ = value;
    }
  }

  /// <summary>Field number for the "autopilot_state" field.</summary>
  public const int AutopilotStateFieldNumber = 10;
  private global::SeiMetadata.Types.AutopilotState autopilotState_ = global::SeiMetadata.Types.AutopilotState.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::SeiMetadata.Types.AutopilotState AutopilotState {
    get { return autopilotState_; }
    set {
      autopilotState_ = value;
    }
  }

  /// <summary>Field number for the "latitude_deg" field.</summary>
  public const int LatitudeDegFieldNumber = 11;
  private double latitudeDeg_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double LatitudeDeg {
    get { return latitudeDeg_; }
    set {
      latitudeDeg_ = value;
    }
  }

  /// <summary>Field number for the "longitude_deg" field.</summary>
  public const int LongitudeDegFieldNumber = 12;
  private double longitudeDeg_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double LongitudeDeg {
    get { return longitudeDeg_; }
    set {
      longitudeDeg_ = value;
    }
  }

  /// <summary>Field number for the "heading_deg" field.</summary>
  public const int HeadingDegFieldNumber = 13;
  private double headingDeg_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double HeadingDeg {
    get { return headingDeg_; }
    set {
      headingDeg_ = value;
    }
  }

  /// <summary>Field number for the "linear_acceleration_mps2_x" field.</summary>
  public const int LinearAccelerationMps2XFieldNumber = 14;
  private double linearAccelerationMps2X_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double LinearAccelerationMps2X {
    get { return linearAccelerationMps2X_; }
    set {
      linearAccelerationMps2X_ = value;
    }
  }

  /// <summary>Field number for the "linear_acceleration_mps2_y" field.</summary>
  public const int LinearAccelerationMps2YFieldNumber = 15;
  private double linearAccelerationMps2Y_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double LinearAccelerationMps2Y {
    get { return linearAccelerationMps2Y_; }
    set {
      linearAccelerationMps2Y_ = value;
    }
  }

  /// <summary>Field number for the "linear_acceleration_mps2_z" field.</summary>
  public const int LinearAccelerationMps2ZFieldNumber = 16;
  private double linearAccelerationMps2Z_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double LinearAccelerationMps2Z {
    get { return linearAccelerationMps2Z_; }
    set {
      linearAccelerationMps2Z_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SeiMetadata);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SeiMetadata other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Version != other.Version) return false;
    if (GearState != other.GearState) return false;
    if (FrameSeqNo != other.FrameSeqNo) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VehicleSpeedMps, other.VehicleSpeedMps)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AcceleratorPedalPosition, other.AcceleratorPedalPosition)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(SteeringWheelAngle, other.SteeringWheelAngle)) return false;
    if (BlinkerOnLeft != other.BlinkerOnLeft) return false;
    if (BlinkerOnRight != other.BlinkerOnRight) return false;
    if (BrakeApplied != other.BrakeApplied) return false;
    if (AutopilotState != other.AutopilotState) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LatitudeDeg, other.LatitudeDeg)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LongitudeDeg, other.LongitudeDeg)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(HeadingDeg, other.HeadingDeg)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LinearAccelerationMps2X, other.LinearAccelerationMps2X)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LinearAccelerationMps2Y, other.LinearAccelerationMps2Y)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LinearAccelerationMps2Z, other.LinearAccelerationMps2Z)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Version != 0) hash ^= Version.GetHashCode();
    if (GearState != global::SeiMetadata.Types.Gear.Park) hash ^= GearState.GetHashCode();
    if (FrameSeqNo != 0UL) hash ^= FrameSeqNo.GetHashCode();
    if (VehicleSpeedMps != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VehicleSpeedMps);
    if (AcceleratorPedalPosition != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AcceleratorPedalPosition);
    if (SteeringWheelAngle != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(SteeringWheelAngle);
    if (BlinkerOnLeft != false) hash ^= BlinkerOnLeft.GetHashCode();
    if (BlinkerOnRight != false) hash ^= BlinkerOnRight.GetHashCode();
    if (BrakeApplied != false) hash ^= BrakeApplied.GetHashCode();
    if (AutopilotState != global::SeiMetadata.Types.AutopilotState.None) hash ^= AutopilotState.GetHashCode();
    if (LatitudeDeg != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LatitudeDeg);
    if (LongitudeDeg != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LongitudeDeg);
    if (HeadingDeg != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(HeadingDeg);
    if (LinearAccelerationMps2X != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LinearAccelerationMps2X);
    if (LinearAccelerationMps2Y != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LinearAccelerationMps2Y);
    if (LinearAccelerationMps2Z != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LinearAccelerationMps2Z);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Version != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Version);
    }
    if (GearState != global::SeiMetadata.Types.Gear.Park) {
      output.WriteRawTag(16);
      output.WriteEnum((int) GearState);
    }
    if (FrameSeqNo != 0UL) {
      output.WriteRawTag(24);
      output.WriteUInt64(FrameSeqNo);
    }
    if (VehicleSpeedMps != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(VehicleSpeedMps);
    }
    if (AcceleratorPedalPosition != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(AcceleratorPedalPosition);
    }
    if (SteeringWheelAngle != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(SteeringWheelAngle);
    }
    if (BlinkerOnLeft != false) {
      output.WriteRawTag(56);
      output.WriteBool(BlinkerOnLeft);
    }
    if (BlinkerOnRight != false) {
      output.WriteRawTag(64);
      output.WriteBool(BlinkerOnRight);
    }
    if (BrakeApplied != false) {
      output.WriteRawTag(72);
      output.WriteBool(BrakeApplied);
    }
    if (AutopilotState != global::SeiMetadata.Types.AutopilotState.None) {
      output.WriteRawTag(80);
      output.WriteEnum((int) AutopilotState);
    }
    if (LatitudeDeg != 0D) {
      output.WriteRawTag(89);
      output.WriteDouble(LatitudeDeg);
    }
    if (LongitudeDeg != 0D) {
      output.WriteRawTag(97);
      output.WriteDouble(LongitudeDeg);
    }
    if (HeadingDeg != 0D) {
      output.WriteRawTag(105);
      output.WriteDouble(HeadingDeg);
    }
    if (LinearAccelerationMps2X != 0D) {
      output.WriteRawTag(113);
      output.WriteDouble(LinearAccelerationMps2X);
    }
    if (LinearAccelerationMps2Y != 0D) {
      output.WriteRawTag(121);
      output.WriteDouble(LinearAccelerationMps2Y);
    }
    if (LinearAccelerationMps2Z != 0D) {
      output.WriteRawTag(129, 1);
      output.WriteDouble(LinearAccelerationMps2Z);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Version != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Version);
    }
    if (GearState != global::SeiMetadata.Types.Gear.Park) {
      output.WriteRawTag(16);
      output.WriteEnum((int) GearState);
    }
    if (FrameSeqNo != 0UL) {
      output.WriteRawTag(24);
      output.WriteUInt64(FrameSeqNo);
    }
    if (VehicleSpeedMps != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(VehicleSpeedMps);
    }
    if (AcceleratorPedalPosition != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(AcceleratorPedalPosition);
    }
    if (SteeringWheelAngle != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(SteeringWheelAngle);
    }
    if (BlinkerOnLeft != false) {
      output.WriteRawTag(56);
      output.WriteBool(BlinkerOnLeft);
    }
    if (BlinkerOnRight != false) {
      output.WriteRawTag(64);
      output.WriteBool(BlinkerOnRight);
    }
    if (BrakeApplied != false) {
      output.WriteRawTag(72);
      output.WriteBool(BrakeApplied);
    }
    if (AutopilotState != global::SeiMetadata.Types.AutopilotState.None) {
      output.WriteRawTag(80);
      output.WriteEnum((int) AutopilotState);
    }
    if (LatitudeDeg != 0D) {
      output.WriteRawTag(89);
      output.WriteDouble(LatitudeDeg);
    }
    if (LongitudeDeg != 0D) {
      output.WriteRawTag(97);
      output.WriteDouble(LongitudeDeg);
    }
    if (HeadingDeg != 0D) {
      output.WriteRawTag(105);
      output.WriteDouble(HeadingDeg);
    }
    if (LinearAccelerationMps2X != 0D) {
      output.WriteRawTag(113);
      output.WriteDouble(LinearAccelerationMps2X);
    }
    if (LinearAccelerationMps2Y != 0D) {
      output.WriteRawTag(121);
      output.WriteDouble(LinearAccelerationMps2Y);
    }
    if (LinearAccelerationMps2Z != 0D) {
      output.WriteRawTag(129, 1);
      output.WriteDouble(LinearAccelerationMps2Z);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Version != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Version);
    }
    if (GearState != global::SeiMetadata.Types.Gear.Park) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GearState);
    }
    if (FrameSeqNo != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(FrameSeqNo);
    }
    if (VehicleSpeedMps != 0F) {
      size += 1 + 4;
    }
    if (AcceleratorPedalPosition != 0F) {
      size += 1 + 4;
    }
    if (SteeringWheelAngle != 0F) {
      size += 1 + 4;
    }
    if (BlinkerOnLeft != false) {
      size += 1 + 1;
    }
    if (BlinkerOnRight != false) {
      size += 1 + 1;
    }
    if (BrakeApplied != false) {
      size += 1 + 1;
    }
    if (AutopilotState != global::SeiMetadata.Types.AutopilotState.None) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AutopilotState);
    }
    if (LatitudeDeg != 0D) {
      size += 1 + 8;
    }
    if (LongitudeDeg != 0D) {
      size += 1 + 8;
    }
    if (HeadingDeg != 0D) {
      size += 1 + 8;
    }
    if (LinearAccelerationMps2X != 0D) {
      size += 1 + 8;
    }
    if (LinearAccelerationMps2Y != 0D) {
      size += 1 + 8;
    }
    if (LinearAccelerationMps2Z != 0D) {
      size += 2 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SeiMetadata other) {
    if (other == null) {
      return;
    }
    if (other.Version != 0) {
      Version = other.Version;
    }
    if (other.GearState != global::SeiMetadata.Types.Gear.Park) {
      GearState = other.GearState;
    }
    if (other.FrameSeqNo != 0UL) {
      FrameSeqNo = other.FrameSeqNo;
    }
    if (other.VehicleSpeedMps != 0F) {
      VehicleSpeedMps = other.VehicleSpeedMps;
    }
    if (other.AcceleratorPedalPosition != 0F) {
      AcceleratorPedalPosition = other.AcceleratorPedalPosition;
    }
    if (other.SteeringWheelAngle != 0F) {
      SteeringWheelAngle = other.SteeringWheelAngle;
    }
    if (other.BlinkerOnLeft != false) {
      BlinkerOnLeft = other.BlinkerOnLeft;
    }
    if (other.BlinkerOnRight != false) {
      BlinkerOnRight = other.BlinkerOnRight;
    }
    if (other.BrakeApplied != false) {
      BrakeApplied = other.BrakeApplied;
    }
    if (other.AutopilotState != global::SeiMetadata.Types.AutopilotState.None) {
      AutopilotState = other.AutopilotState;
    }
    if (other.LatitudeDeg != 0D) {
      LatitudeDeg = other.LatitudeDeg;
    }
    if (other.LongitudeDeg != 0D) {
      LongitudeDeg = other.LongitudeDeg;
    }
    if (other.HeadingDeg != 0D) {
      HeadingDeg = other.HeadingDeg;
    }
    if (other.LinearAccelerationMps2X != 0D) {
      LinearAccelerationMps2X = other.LinearAccelerationMps2X;
    }
    if (other.LinearAccelerationMps2Y != 0D) {
      LinearAccelerationMps2Y = other.LinearAccelerationMps2Y;
    }
    if (other.LinearAccelerationMps2Z != 0D) {
      LinearAccelerationMps2Z = other.LinearAccelerationMps2Z;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Version = input.ReadUInt32();
          break;
        }
        case 16: {
          GearState = (global::SeiMetadata.Types.Gear) input.ReadEnum();
          break;
        }
        case 24: {
          FrameSeqNo = input.ReadUInt64();
          break;
        }
        case 37: {
          VehicleSpeedMps = input.ReadFloat();
          break;
        }
        case 45: {
          AcceleratorPedalPosition = input.ReadFloat();
          break;
        }
        case 53: {
          SteeringWheelAngle = input.ReadFloat();
          break;
        }
        case 56: {
          BlinkerOnLeft = input.ReadBool();
          break;
        }
        case 64: {
          BlinkerOnRight = input.ReadBool();
          break;
        }
        case 72: {
          BrakeApplied = input.ReadBool();
          break;
        }
        case 80: {
          AutopilotState = (global::SeiMetadata.Types.AutopilotState) input.ReadEnum();
          break;
        }
        case 89: {
          LatitudeDeg = input.ReadDouble();
          break;
        }
        case 97: {
          LongitudeDeg = input.ReadDouble();
          break;
        }
        case 105: {
          HeadingDeg = input.ReadDouble();
          break;
        }
        case 113: {
          LinearAccelerationMps2X = input.ReadDouble();
          break;
        }
        case 121: {
          LinearAccelerationMps2Y = input.ReadDouble();
          break;
        }
        case 129: {
          LinearAccelerationMps2Z = input.ReadDouble();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Version = input.ReadUInt32();
          break;
        }
        case 16: {
          GearState = (global::SeiMetadata.Types.Gear) input.ReadEnum();
          break;
        }
        case 24: {
          FrameSeqNo = input.ReadUInt64();
          break;
        }
        case 37: {
          VehicleSpeedMps = input.ReadFloat();
          break;
        }
        case 45: {
          AcceleratorPedalPosition = input.ReadFloat();
          break;
        }
        case 53: {
          SteeringWheelAngle = input.ReadFloat();
          break;
        }
        case 56: {
          BlinkerOnLeft = input.ReadBool();
          break;
        }
        case 64: {
          BlinkerOnRight = input.ReadBool();
          break;
        }
        case 72: {
          BrakeApplied = input.ReadBool();
          break;
        }
        case 80: {
          AutopilotState = (global::SeiMetadata.Types.AutopilotState) input.ReadEnum();
          break;
        }
        case 89: {
          LatitudeDeg = input.ReadDouble();
          break;
        }
        case 97: {
          LongitudeDeg = input.ReadDouble();
          break;
        }
        case 105: {
          HeadingDeg = input.ReadDouble();
          break;
        }
        case 113: {
          LinearAccelerationMps2X = input.ReadDouble();
          break;
        }
        case 121: {
          LinearAccelerationMps2Y = input.ReadDouble();
          break;
        }
        case 129: {
          LinearAccelerationMps2Z = input.ReadDouble();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the SeiMetadata message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum Gear {
      [pbr::OriginalName("GEAR_PARK")] Park = 0,
      [pbr::OriginalName("GEAR_DRIVE")] Drive = 1,
      [pbr::OriginalName("GEAR_REVERSE")] Reverse = 2,
      [pbr::OriginalName("GEAR_NEUTRAL")] Neutral = 3,
    }

    public enum AutopilotState {
      [pbr::OriginalName("NONE")] None = 0,
      [pbr::OriginalName("SELF_DRIVING")] SelfDriving = 1,
      [pbr::OriginalName("AUTOSTEER")] Autosteer = 2,
      [pbr::OriginalName("TACC")] Tacc = 3,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
